// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625180435_AddStockField")]
    partial class AddStockField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Vestes",
                            Image = "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500&q=80",
                            Name = "Veste en Jean Oversize",
                            Price = 59.99m,
                            Stock = 0,
                            Tag = "Nouveau"
                        },
                        new
                        {
                            Id = 2,
                            Category = "T-shirts",
                            Image = "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500&q=80",
                            Name = "T-Shirt Coton Bio Blanc",
                            Price = 24.99m,
                            Stock = 0,
                            Tag = ""
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pantalons",
                            Image = "https://images.unsplash.com/photo-1517423568366-8b83523034fd?w=500&q=80",
                            Name = "Pantalon Cargo Beige",
                            Price = 45.00m,
                            Stock = 0,
                            Tag = "Promo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
